### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by baomihuayu** [ErosZy/WXInlinePlayer#74]
Error: ENOENT: no such file or directory, open '/www/server/wxliline/WXInlinePlayer/lib/codec/bin/h265.asm.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (/www/server/wxliline/WXInlinePlayer/lib/codec/tool/wrapper.js:59:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/www/server/wxliline/WXInlinePlayer/lib/codec/bin/h265.asm.js'
}
+ mv 'combine/prod.*' ../../example
mv: cannot stat ‘combine/prod.*’: No such file or directory

**Comment by RomeoAndJulietAndMe** [comment]
兄弟你的解决了没～
